#!/bin/sh /etc/rc.common
# Service init script untuk menjalankan fancontrol.sh saat booting
START=99

start() {
    chmod +x /usr/bin/fancontrol.sh
    /usr/bin/fancontrol.sh &
}

stop() {
    killall fancontrol.sh 2>/dev/null
}
